HOJA DE TRABAJO 5

In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.preprocessing
import numpy as np
import random
import pyclustertend 
import plotly.express as px
import seaborn as sb
import sklearn.cluster as cluster
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
from sklearn.tree import DecisionTreeRegressor 
from sklearn import tree
from sklearn import metrics
from sklearn.cluster import KMeans
import category_encoders as ce
from sklearn.ensemble import RandomForestClassifier
import statsmodels.api as sm
import statsmodels.stats.diagnostic as smd
from sklearn.linear_model import LinearRegression
from sklearn import datasets
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.linear_model import Ridge
import statsmodels.api as sm
from statsmodels.graphics.gofplots import qqplot
from yellowbrick.regressor import ResidualsPlot
import scipy.stats as stats
import statsmodels.stats.diagnostic as diag
from scipy.stats import normaltest
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score ,precision_score,recall_score,f1_score

1) Use los mismos conjuntos de entrenamiento y prueba que utilizó en las dos hojas anteriores.

In [2]:
datos = pd.read_csv("train.csv", encoding='ISO-8859-1')
datos_cluster = datos[["SalePrice","GarageArea","GarageCars","TotRmsAbvGrd","FullBath","GrLivArea","1stFlrSF", "TotalBsmtSF", "YearBuilt", "OverallQual"]].copy()

In [3]:
y = datos_cluster.pop("SalePrice") #La variable respuesta
X = datos_cluster #El resto de los datos

In [4]:
X_train, X_test,y_train, y_test = train_test_split(X, y,test_size=0.3,train_size=0.7)

2) Elabore un modelo de bayes ingenuo (naive bayes) utilizando el conjunto de entrenamiento 
y explique los resultados a los que llega. El experimento debe ser reproducible por lo que 
debe  fijar  que  los  conjuntos  de  entrenamiento  y  prueba  sean  los  mismos  siempre que se 
ejecute el código.

In [12]:
gaussian = GaussianNB()
gaussian.fit(X_train,y_train)
y_pred = gaussian.predict(X_test)
cm = confusion_matrix(y_test,y_pred)

In [13]:
accuracy=accuracy_score(y_test,y_pred)
precision =precision_score(y_test, y_pred,average='micro')
recall =  recall_score(y_test, y_pred,average='micro')
f1 = f1_score(y_test,y_pred,average='micro')
print('Confusion matrix for Naive Bayes\n',cm)
print('Accuracy: ',accuracy)

Confusion matrix for Naive Bayes
 [[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Accuracy:  0.0045662100456621


3) El modelo debe ser de clasificación, use la variable categórica que hizo con el precio de las 
casas (barata, media y cara) como variable respuesta

4) Utilice  el  modelo  con  el  conjunto  de  prueba  y  determine  la  eficiencia  del  algoritmo  para 
clasificar.

5) Haga  un  análisis  de  la  eficiencia  del  algoritmo  usando  una  matriz  de  confusión.  Tenga  en 
cuenta la efectividad, donde el algoritmo se equivocó más, donde se equivocó menos y la 
importancia que tienen los errores.

6) Analice el modelo. Explique si hay sobreajuste (overfitting) o no.

7) Haga  un  modelo  usando  validación  cruzada,  compare  los  resultados  de  este  con  los  del 
modelo anterior. ¿Cuál funcionó mejor?

8) Compare la eficiencia del algoritmo con el resultado obtenido con el árbol de decisión (el 
de clasificación). ¿Cuál es mejor para predecir? ¿Cuál se demoró más en procesar?